//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mark
    {
        public int SID { get; set; }
        public int ClassId { get; set; }
        public int SubjectID { get; set; }
        public int Marks { get; set; }
    
        public virtual Student Student { get; set; }
    }
}
